# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pV8wDgkU2u7GUl2pr4uo2g_Np5VErfv

# Real-Time Object Detection & Counting

**Author:** Sanae Chakrou  
**Email:** chakrousanae@gmail.com  
**LinkedIn:** [Sanae Chakrou](https://www.linkedin.com/in/sanae-chakrou-561aa0317/)  

---

## Project Overview
A system to **detect and count vehicles in real-time** using **YOLOv8**, **Deep Learning**, and **Computer Vision**.

---

## Features
- Real-time object detection
- Multi-object tracking
- Line-crossing counting
- Annotated output video

---

## How to Run
Open the notebook in **Google Colab** or **Jupyter**.
"""

!pip install ultralytics
!pip install supervision

import ultralytics
ultralytics.__version__
import supervision
import torch  #framework that makes YOLOv8 run efficiently

torch.cuda.get_device_name(0)

from google.colab import drive
drive.mount('/content/drive')

input_video = "/content/drive/MyDrive/detection and counting project/d.mp4"
output_folder = "/content/drive/MyDrive/detection and counting project/predict"

from ultralytics import YOLO
#import pretrained YOLOv8n model
model = YOLO('yolov8n.pt')
model.predict(source= input_video, save=True, imgsz=640, conf=0.5, project=output_folder, name='result')

"""TRACKING"""

from ultralytics import YOLO
#configure the tracking parameter and run the tracker
model = YOLO('yolov8n.pt')
model.track(source=input_video, save=True,  project=output_folder, conf=0.3, iou=0.5, tracker='bytetrack.yaml')



"""TRACKING AND COUNTING"""
import cv2
from collections import defaultdict
import supervision as sv
from ultralytics import YOLO

# Load YOLOv8 model
model = YOLO('yolov8n.pt')

# Define the counting line coordinates
Start = sv.Point(182, 254)
End = sv.Point(462, 254)

start_sideline = sv.Point(198,250)
end_sideline = sv.Point(238, 202)

# Dictionaries to store tracking history and crossed objects
track_history = defaultdict(lambda : [])

#dictionary for the main line
crossed_object_main = {}

#dictionary for the sideline
crossed_object_sideline = {}


# Path to input video
video_path = "/content/drive/MyDrive/detection and counting project/d.mp4"
input_video = cv2.VideoCapture(video_path)

# Setup video sink for saving the annotated video
video_info = sv.VideoInfo.from_video_path(video_path)
with sv.VideoSink('/content/drive/MyDrive/detection and counting project/output_2lines.mp4', video_info) as sink:

    while input_video.isOpened():
        success, frame = input_video.read()
        if not success:
            break

        # Run YOLOv8 tracking on the frame
        results = model.track(
            source=frame,
            tracker='bytetrack.yaml',
            classes=[2,3,5,7],  # Vehicle classes (example)
            persist=True,
            save=False
        )

        # Get boxes and track IDs
        boxes = results[0].boxes.xywh.cpu()
        track_ids = results[0].boxes.id.int().cpu().tolist()

        # Annotate the frame
        annotated_frame = results[0].plot()

        # Track objects and count crossings
        for box, track_id in zip(boxes, track_ids):
            x, y, w, h = box
            track = track_history[track_id]
            track.append((float(x), float(y)))  # Center points

            if len(track) > 30:  # Keep last 30 positions
                track.pop(0)

            # Check if object crossed the main line
            if Start.x < x < End.x and abs(y - Start.y) < 5:
                if track_id not in crossed_object_main:
                    crossed_object_main[track_id] = True

            # Check if object crossed the sideline
            if start_sideline.x < x < end_sideline.x and min(start_sideline.y, end_sideline.y) < y < max(start_sideline.y, end_sideline.y):
                if track_id not in crossed_object_sideline :
                    crossed_object_sideline[track_id] = True


            

                # Annotate the object as crossed
                cv2.rectangle(
                    annotated_frame,
                    (int(x - w/2), int(y - h/2)),
                    (int(x + w/2), int(y + h/2)),
                    (0, 255, 0),
                    2
                )

        # Draw the counting line
        cv2.line(annotated_frame, (Start.x, Start.y), (End.x, End.y), (0, 255, 0), 2)
        cv2.line(annotated_frame, (start_sideline.x, start_sideline.y), (end_sideline.x, end_sideline.y), (0,0,255), 2)

        # Show count of objects crossed
        count_main_text = f"Objects crossed main line: {len(crossed_object_main)}"
        count_sideline_text = f"Objects crossed sideline: {len(crossed_object_sideline)}"


        cv2.putText(annotated_frame,count_main_text,(10, 30),cv2.FONT_HERSHEY_SIMPLEX,1,(0, 255, 0),2 )
        cv2.putText(annotated_frame, count_sideline_text, (10,70), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2)

        # Write annotated frame to output video
        sink.write_frame(annotated_frame)

# Release the input video
input_video.release()
print("Processing complete! Output saved as 'output_video.mp4'.")





